# Generated by Django 5.2.7 on 2025-10-14 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='product_name')),
                ('img', models.ImageField(upload_to='images', verbose_name='product_img')),
                ('price', models.PositiveIntegerField(verbose_name='product_price')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_id', to='shop.category')),
            ],
        ),
    ]
